version: '3'
services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the path to your Dockerfile
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    volumes:
      - .:/app  # Mount the current directory into the container's /app directory
    environment:
      - NODE_ENV=production  # Set NODE_ENV to 'production' (adjust as needed)
    command: npm start