on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
  
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3A
    
    - name: Set up SSH
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJP1dKOubZG3K2vezFyE5PjmA0ikP4zWhbR3pIhhcuqP" > ~/.ssh/id_ed25519.pub
        cat ~/.ssh/id_rsa
        cat ~/.ssh/known_hosts
      
    - name: Connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && chmod +x ./pull.sh && ./pull.sh && exit"
      
    - name: Cleanup
      run: rm -rf ~/.ssh