name: deploy to a server on push

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:

    - uses: appleboy/ssh-action@master 
      with:
        host: 34.116.255.23
        username: github
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script:
          mikdir bylemtu
          