name: Docker Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-action@v2

      - name: Build Docker image
        run: |
          chmod +x build-docker.sh
          ./build-docker.sh
        env:
          PORT: ${{ secrets.PORT }}  # Use GitHub secrets to store sensitive information

      - name: Run Docker container
        run: |
          chmod +x run-docker.sh
          ./run-docker.sh
        env:
          PORT: ${{ secrets.PORT }}  # Use GitHub secrets to store sensitive information

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Stop and remove Docker container
        run: |
          chmod +x cleanup-docker.sh
          ./cleanup-docker.sh
        continue-on-error: true  # Continue even if container or image does not exist
